apiVersion: backstage.io/v1alpha1
kind: test-backstage
metadata:
  name: test
  annotations:
    github.com/project-slug: McalfinM/test-backstage
spec:
  type: other
  lifecycle: unknown
  owner: TS-BE
  
catalog:
  locations:
    - type: url
      target: https://github.com/McalfinM/test-backstage
      metadata:
        type: template
        name: my-template
        description: My custom template
